---
- hosts: all
  tasks:
  - name: add megacli to source list 
    apt_repository: 
      repo: deb http://mirror.rackspace.com/hwraid.le-vert.net/debian/ jessie main
      state: present

  - name: install PGP signature
    apt_key:
      url: https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key
      state: present

  - name: apt-get update
    apt:
      update_cache: yes

  - name: install megacli
    package:
      name: megacli 
      state: present
